version: '2'

networks:
  app-tier:
    driver: bridge

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=playground
      - RABBITMQ_PASSWORD=playground
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ~/docker_data/rabbitmq:/bitnami
    networks:
      - app-tier
