prettyPrint: true
openAPI:
  info:
    version: '0.1'
    title: Playground application API
    description: 'Playground application is a sandbox to evaluate JEE related concepts.
        This API provides resources helpful for hacking the code ;): register, login, and play with other secured stuff.'
    contact:
      email: jacek.olszewski@gmail.com
    license:
      name: MIT
      url: https://en.wikipedia.org/wiki/MIT_License